---
title: "Frequently asked question (FAQ)"
author: "Justin Wilkins & Mike K Smith"
date: 2017-01-17T12:00:00Z
tags: ["FAQ"]
output: html_document
---
## What does Thoughtflow mean?
Put simply, Thoughtflow is the name we have given to a set of standards developed by the DDMoRe consortium to facilitate the
capture, storage, and reporting of knowledge (including assumptions and decisions) in the context of model-informed drug
discovery and development (MID3), as well as to support reproducibility. Eventually, it might be the name of the tool we plan to create.

## Why do we need this?
### Why develop a new tool?
There isn't anything out there that can do the job that we want it to do.

### Why create a new standard?
Standards are the bedrock upon which the tools will be built. We wish to avoid a situation in which we have a range of open and commercial tools that meet this need, but none are able to talk to one another.

### What's the difference between this and any other workflow capture tool?
There are a range of tools available in the marketplace,
both commercial and open source, for supporting workflows
of executable, computational tasks and tracking the provenance
of workflow executions. [Taverna](http://www.taverna.org.uk/), [KNIME](https://www.knime.org/), [Kepler](https://kepler-project.org/),
[Activiti](http://activiti.org), [Navigator](http://www.mango-solutions.com/wp/products-services/products/navigator/), [Improve](http://www.scinteco.com/), and
[Pipeline Pilot](http://accelrys.com/products/collaborative-science/biovia-pipeline-pilot/) are some examples.

While these tools are all competent at handling workflows,
noncomputational tasks, such as making inferences and
decisions based on analytical results, are equally important
when tracking and reporting pharmacometrics analyses. It was clear after our
assessment of the available tools that a platform able to
capture computational tasks, business processes, and the
interactions between them was required.

### But I already use git...
[git](https://git-scm.com/) is a good start, and is indeed built into the Thoughtflow design, but we can do so much better.

## How do I get started?
Join the Thoughtflow Community Group and help us build the future!

## What will the tool look like?
The demonstrator prototype is built using [Java](http://www.java.com/) and [R](http://www.r-project.org/), but the final shape and form is yet to be determined. We will decide this as a group based on the needs of academia, industry and regulators.

## What has already been done?
Everything developed during the DDMoRe project can be found in our [GitHub repository](https://github.com/DDMoReThoughtflow). A [technical document](../post/Capturing_Pharmacometrics_Workflow_Concepts_with_PROV-O_311016.pdf) has been prepared outlining our approach, and a position paper describing the Thoughtflow philiosophy, and how it might be used as the basis for a tool, will be published in [CPT:PSP](http://ascpt.onlinelibrary.wiley.com/hub/journal/10.1002/(ISSN)2163-8306/) in the first quarter of 2017.

## How can I get hold of you?
Issues, bugs, feature requests, suggestions can be logged via 
the [Github Issues page](https://github.com/DDMoReThoughtflow/website/issues).

Please label your item with "Website", "provr", "GUI", "store-server" or 
"infrastructure" and the type of issue ("bug","enhancement","help wanted",
"invalid","question") so that we can direct it to the right place for action.  



