baseurl = "http://www.thoughtflow.community/"
languageCode = "en-us"
title = "DDMoRe Thoughtflow Community Group"
# Enable comments by entering your Disqus shortname
disqusShortname = "ddmore-thoughtflow"
# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-91241151-1"
# Define the number of posts per page
paginate = 10
footnotereturnlinkcontents = "↩"
theme = "hugo-icarus-theme"
publishdir = "docs"

[permalinks]
    post = "/:year/:month/:day/:slug"


[params]
    # Tell me who you are
    author = "DDMore Thoughtflow Community Group"
    bio = "Redefining workflows in pharmacometrics"
    location = "Earth"
    site_description = "Providing a resource for learning about provenance and workflow capture, associated tools and technology in the context of model informed drug discovery and development (MID3)."
    copyright  = "(c) 2017 DDMoRe Thoughtflow Community Group"
    avatar = "css/images/thoughtflow.png"
    logo = "css/images/thoughtflow.png"
    disable_mathjax = false # set to true to disable MathJax

    # Format dates with Go's time formatting
    date_format = "2006-01-02"

    # Add custom assets with their paths relative to the static folder
	custom_css = []
	custom_js  = []

# Create custom menu entries by defining a label and a link for
# them. Since you can also link posts, you've the option the
# place the links before or after them.
#
# E.g.: "Home" appears before all linked posts in the menu
# and "Tags" / "Categories" after them.
[[params.menu]]
    before = true
    label  = "Blog"
    link   = "/"

[[params.menu]]
    before = false
    label  = "Documents"
    link   = "/page/download/"

[[params.menu]]
    before = false
    label  = "FAQ"
    link   = "/page/faq/"

[[params.menu]]
    before = false
    label  = "About"
    link   = "/page/about/"
    
# Enter a link for the follow button on the left
[params.profile]
    follow_button = "https://github.com/DDMoReThoughtflow"


[social]
# Add your social network accounts to the profile section on the left
# by entering your username. The links to your account will be
# created automatically.
    github          = "DDMoReThoughtflow"
    gitlab          = ""
    bitbucket       = ""
    jsfiddle        = ""
    codepen         = ""
    foursquare      = ""
    dribbble        = ""
    deviantart      = ""
    behance         = ""
    flickr          = ""
    instagram       = ""
    youtube         = ""
    vimeo           = ""
    vine            = ""
    medium          = ""
    wordpress       = ""
    tumblr          = ""
    xing            = ""
    linkedin        = ""
    slideshare      = ""
    stackoverflow   = ""
    reddit          = ""
    pinterest       = ""
    googleplus      = ""
    facebook        = ""
    facebook_admin  = ""
    twitter_domain  = ""
    twitter         = "DD_Thoughtflow"

# Enable and disable widgets for the right sidebar
[params.widgets]
    recent_articles = true
    categories = true
    tags = true
    tag_cloud = true
