---
title: "Welcome to Thoughtflow!"
author: "Justin Wilkins & Mike K Smith"
date: 2017-01-17T12:00:00Z
tags: ["About", "website"]
output: html_document
---
## Welcome to the DDMoRe Thoughtflow Community Group!
This website serves as the home for the Thoughtflow Community Group, including 
all of our code and resources for anyone wishing to learn
about provenance and workflow capture, associated tools and 
technologies in the context of model informed drug discovery
and development (MID3). Thoughtflow was initially developed as part
of the [IMI DDMoRe project](http://ddmore.eu/product/pharmacometric-workflow).

### What is Thoughtflow?
Thoughtflow is a combination of workflow capture (inputs to outputs), 
provenance capture (what output entities are associated with input entities,
activities, and agents), querying and manipulation of provenance information 
from a database of provenance information.

### Where can I find details about provenance, PROV-O and Thoughtflow?
The IMI DDMoRe project has produced a [draft technical document](Capturing_Pharmacometrics_Workflow_Concepts_with_PROV-O_311016.pdf) about the use of provenance capture
using the [PROV-O ontology](https://www.w3.org/TR/prov-o/) as the basis for 
a controlled vocabulary of provenance. An accompanying white paper will be published in
[http://ascpt.onlinelibrary.wiley.com/hub/journal/10.1002/(ISSN)2163-8306/](Clinical Pharmacology & Therapeutics: Pharmacometrics & Systems Pharmacology) in the first quarter of 2017.

### What's next?
This afternoon, the first kickoff meeting for the DDMoRe Foundation's Community Groups 
will take place. This is where we hope to recruit our team 

### Authors and Contributors
Justin Wilkins [@kestrel99](https://github.com/kestrel99)
Mike K Smith [@MikeKSmith](https://github.com/MikeKSmith)  
Ed Watson [@tactmaster](https://github.com/tactmaster)  
Stuart Moodie [@stumoodie](https://github.com/stumoodie)

### Support or Contact
Issues, bugs, feature requests, and suggestions can be logged via 
the [Github Issues page](https://github.com/DDMoReThoughtflow/website/issues).
Please label your item with "Website", "provr", "GUI", "store-server" or 
"infrastructure" and the type of issue ("bug","enhancement","help wanted",
"invalid","question") so that we can direct it to the right place for action.  

Email contact information will be added very soon.

### Acknowledgements
The research leading to these results received support from the [Innovative Medicines Initiative Joint Undertaking](http://www.imi.europa.eu/) under grant agreement no 115156, resources of which are composed of financial contribution from the [European Union's Seventh Framework Programme (FP7/2007-2013)](https://ec.europa.eu/research/fp7/index_en.cfm) and [EFPIA](https://www.efpia.eu) companies' in-kind contribution. The DDMoRe project was also financially supported by contributions from academic and SME partners.
