---
title: "About Thoughtflow and this website"
author: "AN Other"
date: 2016-12-12T10:00:00Z
tags: ["About", "website"]
output: html_document
---
## Welcome to the DDMoRe Thoughtflow Community page.
This website will provide a resource for anyone wishing to learn
about provenance and workflow capture, associated tools and 
technologies in the context of model informed drug discovery
and development (MID3). Thoughtflow was initially developed as part
of [the IMI DDMoRe project](http://ddmore.eu/product/pharmacometric-workflow).

### What is Thoughtflow?
Thoughtflow is a combination of workflow capture (inputs to outputs), 
provenance capture (what output entities are associated with input entities,
activities, and agents), querying and manipulation of provenance information 
from a database of provenance information.

### Where can I find details about provenance, Prov-O and Thoughtflow?
The IMI DDMoRe project produced a [White Paper] about use of provenance capture
using the [PROV-O ontology](https://www.w3.org/TR/prov-o/) as the basis for 
a controlled vocabulary of provenance.

### What is coming on this website?
In the near future we hope to provide: 

* Foo
* bar

### Authors and Contributors
Mike K Smith [@MikeKSmith](https://github.com/MikeKSmith)  
Justin Wilkins [@kestrel99](https://github.com/kestrel99)  
Ed Watson [@tactmaster](https://github.com/tactmaster)  

### Support or Contact
Issues, bugs, feature requests, suggestions can be logged via 
the [Github Issues page](https://github.com/DDMoReThoughtflow/website/issues).
Please label your item with "Website", "provr", "GUI", "store-server" or 
"infrastructure" and the type of issue ("bug","enhancement","help wanted",
"invalid","question") so that we can direct it to the right place for action.  

Email contact information will be added very soon.

### Acknowledgements
The research leading to these results has received support from the Innovative Medicines Initiative Joint Undertaking under grant agreement n° 115156, resources of which are composed of financial contribution from the European Union's Seventh Framework Programme (FP7/2007-2013) and EFPIA companies’ in kind contribution. The DDMoRe project is also financially supported by contributions from Academic and SME partners.